@url_dev =  http://localhost:8080/v1/api
@jwt_token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTIzMzEwNDksInVzZXJfaWQiOiJhYjYzMjQwYi04OTRkLTRjNjAtOTc3Yy1mYzhmNzRhY2U2NzkifQ.k--e3g7NEplGTkHoMcxLyGdDMZYRi1C8KXgxKxswZ1gvke0u5ayV56jF6PwDoCUPy_FyLfqjl2i1xMRmpvSfCHlwgOKS_S2uX6wTiN3bOagYADIjNhlYA9a041h7JlWnf5b16YBowvMcGOTGis01Z9GcINp1glZQYyXTrPCG2rzU5hrShBZUaOCg67Q1VNjE_4cf61Lg6Jbys9sgUI1rm_W_EnK2QblCfK-MSvdXoKAypAqn8kj8v-ws0ouJslN7IcbCc2nCQtsD0YhZhpdLYyCbAUTuPC74G99nXKuJX_tU8_aBrsClwFFW7mRklckBpv102hM1AZCCfCjgTbSSow

### create a new book
POST {{url_dev}}/books/
Authorization: Bearer {{jwt_token}}

{
  "title": "Clean Architecture 2",
  "author": "Robert C. Martin",
  "price": "29.99"
}

### get 1 book
GET {{url_dev}}/books/5aa919ee-abf8-496b-b6c6-f62825319793

### get all books
GET {{url_dev}}/books/
Authorization: Bearer {{jwt_token}}

### update a book
PUT {{url_dev}}/books/5aa919ee-abf8-496b-b6c6-f62825319793

{
  "title": "Clean Architecture 2",
  "author": "Robert C. Martin",
  "price": "35.99"
}

### delete a book
DELETE {{url_dev}}/books/5aa919ee-abf8-496b-b6c6-f62825319793

### register a new user
POST {{url_dev}}/auth/register

{
  "username": "john_doe",
  "password": "securepassword"
}

### login a user
POST {{url_dev}}/auth/login

{
  "username": "john_doe",
  "password": "securepassword"
}
