class DomainError(Exception):
    """Base cho lỗi nghiệp vụ thuần (không dính HTTP)."""
    pass

class UserNotFound(DomainError): ...
class BookNotFound(DomainError): ...
class EmailAlreadyExists(DomainError): ...
class InvalidCredentials(DomainError): ...
class InvalidEmail(DomainError): ...
class PasswordTooWeak(DomainError): ...
