"""add tracking fields to books

Revision ID: 2a71dda90b57
Revises: 9cf9bbbe21ef
Create Date: 2025-08-20 15:21:50.004089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a71dda90b57'
down_revision: Union[str, Sequence[str], None] = '9cf9bbbe21ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('books', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('books', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('books', sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.drop_index(op.f('uq_books_title_author_ci'), table_name='books')
    op.create_index('ix_books_category_updated', 'books', ['category', 'updated_at'], unique=False)
    op.create_index(op.f('ix_books_deleted_at'), 'books', ['deleted_at'], unique=False)
    op.create_index('ix_books_updated_at', 'books', ['updated_at'], unique=False)
    op.create_index('uq_books_title_author_ci_active', 'books', [sa.literal_column('lower(title)'), sa.literal_column('lower(author)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_books_title_author_ci_active', table_name='books', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_books_updated_at', table_name='books')
    op.drop_index(op.f('ix_books_deleted_at'), table_name='books')
    op.drop_index('ix_books_category_updated', table_name='books')
    op.create_index(op.f('uq_books_title_author_ci'), 'books', [sa.literal_column('lower(title::text)'), sa.literal_column('lower(author::text)')], unique=True)
    op.drop_column('books', 'version')
    op.drop_column('books', 'deleted_at')
    op.drop_column('books', 'updated_at')
    op.drop_column('books', 'created_at')
    # ### end Alembic commands ###
