"""add field age into users table

Revision ID: 94b251475ba9
Revises: 2a71dda90b57
Create Date: 2025-08-22 09:39:08.680217

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "94b251475ba9"
down_revision: Union[str, Sequence[str], None] = "2a71dda90b57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("age", sa.Integer(), nullable=False))
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "name", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.drop_column("users", "age")
    # ### end Alembic commands ###
