"""add constraints to books

Revision ID: 9cf9bbbe21ef
Revises: f68367d2223e
Create Date: 2025-08-20 13:43:06.345070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf9bbbe21ef'
down_revision: Union[str, Sequence[str], None] = 'f68367d2223e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_books_title_author_ci', 'books', [sa.literal_column('lower(title)'), sa.literal_column('lower(author)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_books_title_author_ci', table_name='books')
    # ### end Alembic commands ###
