// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package authsdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Auth struct {
	ID        pgtype.UUID
	Username  string
	Password  string
	CreatedAt pgtype.Timestamp
}

type Book struct {
	ID        pgtype.UUID
	Title     string
	Author    string
	Price     pgtype.Numeric
	CreatedAt pgtype.Timestamp
}

type RefreshToken struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	Revoked   pgtype.Bool
}
