class UseCaseError(Exception):
    """Base cho lỗi tầng ứng dụng (flow/orchestration)."""
    pass

class NotFound(UseCaseError): ...
class Unauthorized(UseCaseError): ...
class BadRequest(UseCaseError): ...
class Conflict(UseCaseError): ...
class Forbidden(UseCaseError): ...