// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package usersdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID        pgtype.UUID
	Title     string
	Author    string
	Price     pgtype.Numeric
	CreatedAt pgtype.Timestamp
}

type User struct {
	ID        pgtype.UUID
	Username  string
	Password  string
	CreatedAt pgtype.Timestamp
}
